
.rj 5
Guruprasad
.br
Analog Design Engineer 
.br
E-mail: gurupr@karmic.co.in 
.br
Ph: 9482098406 
.br
Web page: https://guru-gitrepo.github.io 

.SH
Preofessional Summary
.LP
Analog Design Engineer with hands-on experience in LDO and power-management circuits in TI CMOS processes.
Worked on Texas Instruments client projects involving block-level LDO design support and simulation, PVT and Monte-
Carlo analysis, trimming, aging, and post-layout simulations. Experienced in silicon/IP-level characterization of non-
volatile memories, VCO, HVGEN, and EEPROM IPs, including testbench development without data sheets. Strong back-
ground in analog fundamentals, PMIC blocks, and Cadence Spectre-based design flow.

.SH
Core skills
.IP
\f[B]Analog Blocks:\f[] LDO, Bandgap, Op-Amps, Comparators, POR, Voltage References
.IP
\f[B]PMIC Concepts:\f[] Stability, PSRR, Load Transient, Compensation, Trimming
.IP
\f[B]Verification:\f[] PVT, Monte-Carlo, Aging, Burn-in, Corner Analysis
.IP
\f[B]Simulation & Analysis:\f[] AC, Transient, Noise, Stability analysis
.IP
\f[B]EDA Tools:\f[] Cadence Virtuoso, Spectre, ADE
.IP
\f[B]Technology:\f[] TI pdks

.SH
Texas Instruments : Client Projects (via KarMic Design)
.IP 1. 4
\f[B]NMOS LDO Design:\f[]
.RS
.IP \[bu] 3
Bias circuit modification and block-level design support and verification of
NMOS LDO.
.IP \[bu]
PVT, Monte-Carlo, aging, and burn-in simulations
.IP \[bu]
Line/load regulation, PSRR, stability, startup, and load transient analysis
.IP \[bu]
Resistor trimming and post-layout simulation support
.RE

.IP 2. 4
\f[B]Embedded Memory & NVM IP Characterization\f[]
.RS
.IP \[bu] 3
 Worked on EEPROM, MTP, and NVM IPs across multiple TI technologies.
.IP \[bu]
Developed testbenches for IDDQ, program/read currents, margin testing.
.IP \[bu]
External IREF margin characterization across PVT and Monte-Carlo (up to 1000 samples per corner)
.IP \[bu]
Post-burn and post-bake current analysis and data extraction.
.RE

.IP 3.
\f[B]High-Voltage Generator & VCO IP Testing\f[]
.RS
.IP \[bu] 3
HVGENMINILV / HVGENMINIMVAL IP characterization.
.IP \[bu]
Designed testbenches to measure IDDQ, frequency vs control voltage.
.IP \[bu]
Verified VCO performance across temperature and process corners.
.IP \[bu]
Supported performance improvement through circuit-level modifications.
.RE
.LP
